version: '2'
services:
  schnitzler-briefe:
    image: "acdh/schnitzler-briefe"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/tmp/export
