version: '2'
services:
  arthur-schnitzler-briefe:
    image: "acdh/arthur-schnitzler-briefe"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/tmp/export
