version: '2'
services:
  schnitzler-briefe:
    image: "acdh/schnitzler-briefe"
    labels:
      - traefik.backend=schnitzler-briefe
      - traefik.frontend.rule=Host:schnitzler-briefe.sisyphos.arz.oeaw.ac.at
      - traefik.docker.network=web
      - traefik.port=8080
    networks:
      - web
    build:
      context: .
      dockerfile: Dockerfile
networks:
  web:
    external:
      name: web
